version: "3.3"
services:
  mysql:
    image: mysql:8.0.18
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=shop
    networks:
      - shop
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1
networks:
  shop:
    external: true